### ISSUE TITLE
Review 1 presentation preperation

### ISSUE THREAD

**Issue by SasaKuruppuarachchi** [SasaKuruppuarachchi/adaptive_estimation#21]

**Comment by EternalGoldenBraid** [comment]
See some thoughts from here: https://github.com/SasaKuruppuarachchi/adaptive_estimation/issues/34

**Comment by EternalGoldenBraid** [comment]
Please prepare a 10min presentation, with focus on:
- the goals
- results so far (e.g., show simulation results),
- and changes in the plan (updated schedule).

**Comment by SasaKuruppuarachchi** [comment]
# Nick
- Review LQR
- Make slides


### Changes in the plan:
- Dotted line from estimation to control
- Limit the scope of the research project:
    - Performance difference in estimation between eKF and tPC
    - Focus on qualitative and quantitative differences in tPC and different controllers (PID vs. LQR vs eLQR)
    - Target a publication in 6 months.

### TODOs
- Validate eKF implementation
- Understand role model dt in tPC state update step sizes and model update step sizes.


### Goals (both sim and on device)
1. Pure state estimation no control
2. tPC + PID control
3. tPC + LQR with linearised dynamics
4. tPC + eLQR


### Results so far
- Setting up Isaac Sim (video)
- Setting up Gymnasium (video)
