### ISSUE TITLE
Meeting Sasa&Nick&Gökhan&Iman

### ISSUE THREAD

**Issue by EternalGoldenBraid** [SasaKuruppuarachchi/adaptive_estimation#30]
### Gökhans pointers
- Choose a suitable level of researchy vs practical work.
- Limit the scope from trying out everything to a few things.
  - E.g. compare pros and cons of LQR and PID with tPC state estimation.
- Implement in steps:
  - Estimation without control
    - Does the system behave as expected?
  - Add control

### General remarks
- LQR we require a model of the system. I.e. $C$ and thus states must be sensible.
- PID is more robust to model errors and we only care about observations.
- Magnets for modifying physical system.
- Don't worry about MPC for now.

**Comment by SasaKuruppuarachchi** [comment]
## Regarding the uncertain tracking of the state
- The system is optimising for too many outputs/parameters
- Try fixing C matrix to I for example

## Control Scheme
- Compare performance with PID and LQR
- With PID output of the state estimator does not need to be outputting the exact state
- With the changing model (A) LQR will show interesting results
- As the Second order information is produced in the estimator, it is good to send them to LQR 
- LQR is time invariant so this is good. (MPC is not as it is iterative)

## Regarding the research
- Limit the scenario to one line of the story to help publications within 6 months
- Drop MPC for now
