### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by EternalGoldenBraid** [SasaKuruppuarachchi/adaptive_estimation#32]
Go through the agent-gymnasium code and isaac sim code to make sure we're compatible.
- https://github.com/SasaKuruppuarachchi/adaptive_estimation/blob/main/tpc/src/tpc/simulator/gymnasium_simulator.py

**Comment by SasaKuruppuarachchi** [comment]
- the ROS geometry message ref [here](https://docs.ros.org/en/noetic/api/geometry_msgs/html/index-msg.html)

**Comment by EternalGoldenBraid** [comment]
- Sasa set up communication
  - Sim:
    - gt state
    - observation
  - Controls:
    - theta
    - Ros (service etc...) to receiv 

- Nicklas
  - Estimate theta directly
  - Set up service for action-observation between agent and sim.
  - Agent as a service the waits for sim node to request for action.
    - Sim node passes observation as a msg in the request.
  - Sim:
    - Make into a node such that we can call self.action_service
  - Agent:
    - Advertise the service and wait for request.
